"""empty message

Revision ID: 2fb9fed8f672
Revises: bd3283f54e39
Create Date: 2020-03-12 16:07:14.473188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fb9fed8f672'
down_revision = 'bd3283f54e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('task_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'task', ['task_id'], ['id'])
    op.drop_column('comment', 'id_task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('id_task', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'task', ['id_task'], ['id'])
    op.drop_column('comment', 'task_id')
    # ### end Alembic commands ###
