"""empty message

Revision ID: 36427f7b63b4
Revises: 3bc71c7e1ca6
Create Date: 2020-06-13 14:23:10.480216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36427f7b63b4'
down_revision = '3bc71c7e1ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('final', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('inceput', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'inceput')
    op.drop_column('task', 'final')
    # ### end Alembic commands ###
