"""empty message

Revision ID: 46bd1156c302
Revises: ef931983f95d
Create Date: 2020-06-14 22:20:44.421881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46bd1156c302'
down_revision = 'ef931983f95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('minuteBiliard', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('minuteBowling', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('minuteDarts', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('minuteTotal', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('nrBiliard', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('nrBowling', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('nrDarts', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('nrPuncte', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('nrTotal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nrTotal')
    op.drop_column('user', 'nrPuncte')
    op.drop_column('user', 'nrDarts')
    op.drop_column('user', 'nrBowling')
    op.drop_column('user', 'nrBiliard')
    op.drop_column('user', 'minuteTotal')
    op.drop_column('user', 'minuteDarts')
    op.drop_column('user', 'minuteBowling')
    op.drop_column('user', 'minuteBiliard')
    # ### end Alembic commands ###
