"""empty message

Revision ID: 5452786e9165
Revises: ab6d4849b3fe
Create Date: 2020-02-20 14:03:27.733351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5452786e9165'
down_revision = 'ab6d4849b3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint('task_ibfk_3', 'task', type_='foreignkey')
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('task_ibfk_3', 'task', 'user', ['user_id'], ['id'])
    op.drop_column('task', 'updated_at')
    op.drop_column('task', 'due_date')
    op.drop_column('task', 'created_at')
    op.drop_column('label', 'updated_at')
    # ### end Alembic commands ###
