"""empty message

Revision ID: 645268d4d13e
Revises: 7f9909cf7eaa
Create Date: 2020-06-14 11:46:27.769902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645268d4d13e'
down_revision = '7f9909cf7eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('nrBiliard', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('nrBowling', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('nrDarts', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('nrPuncte', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('nrTotal', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('oreBiliard', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('oreBowling', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('oreDarts', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('oreTotal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'oreTotal')
    op.drop_column('user', 'oreDarts')
    op.drop_column('user', 'oreBowling')
    op.drop_column('user', 'oreBiliard')
    op.drop_column('user', 'nrTotal')
    op.drop_column('user', 'nrPuncte')
    op.drop_column('user', 'nrDarts')
    op.drop_column('user', 'nrBowling')
    op.drop_column('user', 'nrBiliard')
    op.drop_column('user', 'is_admin')
    op.drop_table('produs')
    # ### end Alembic commands ###
