"""empty message

Revision ID: 7cc439015381
Revises: 1bf3ce3f8f09
Create Date: 2020-02-28 14:50:14.515743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc439015381'
down_revision = '1bf3ce3f8f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_task', sa.Integer(), nullable=True),
    sa.Column('comment_user_id', sa.Integer(), nullable=True),
    sa.Column('comment_body', sa.Text(), nullable=True),
    sa.Column('comment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_task'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
