"""empty message

Revision ID: 7f9909cf7eaa
Revises: 36427f7b63b4
Create Date: 2020-06-13 15:01:37.163769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f9909cf7eaa'
down_revision = '36427f7b63b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('finalH', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('finalM', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('inceputH', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('inceputM', sa.Integer(), nullable=True))
    op.drop_column('task', 'inceput')
    op.drop_column('task', 'final')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('final', mysql.DATETIME(), nullable=True))
    op.add_column('task', sa.Column('inceput', mysql.DATETIME(), nullable=True))
    op.drop_column('task', 'inceputM')
    op.drop_column('task', 'inceputH')
    op.drop_column('task', 'finalM')
    op.drop_column('task', 'finalH')
    # ### end Alembic commands ###
