"""empty message

Revision ID: 82f56bc66652
Revises: 7cc439015381
Create Date: 2020-02-28 14:55:37.842981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82f56bc66652'
down_revision = '7cc439015381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_task', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('comment_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('comment_body', mysql.TEXT(), nullable=True),
    sa.Column('comment_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['comment_user_id'], ['user.id'], name='comment_ibfk_1'),
    sa.ForeignKeyConstraint(['id_task'], ['task.id'], name='comment_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
