"""empty message

Revision ID: ab6d4849b3fe
Revises: 189b9f4c04f0
Create Date: 2020-02-18 15:29:37.667201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6d4849b3fe'
down_revision = '189b9f4c04f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'created_at')
    # ### end Alembic commands ###
