"""empty message

Revision ID: bb0a748bc30c
Revises: 2fb9fed8f672
Create Date: 2020-03-13 11:01:03.863884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb0a748bc30c'
down_revision = '2fb9fed8f672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', mysql.VARCHAR(length=80), nullable=True))
    # ### end Alembic commands ###
