"""empty message

Revision ID: bef4a9bdbeca
Revises: 645268d4d13e
Create Date: 2020-06-14 18:49:07.712327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bef4a9bdbeca'
down_revision = '645268d4d13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('minuteBiliard', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('minuteBowling', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('minuteDarts', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('minuteTotal', sa.Float(), nullable=True))
    op.drop_column('user', 'oreTotal')
    op.drop_column('user', 'oreBiliard')
    op.drop_column('user', 'oreBowling')
    op.drop_column('user', 'oreDarts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oreDarts', mysql.FLOAT(), nullable=True))
    op.add_column('user', sa.Column('oreBowling', mysql.FLOAT(), nullable=True))
    op.add_column('user', sa.Column('oreBiliard', mysql.FLOAT(), nullable=True))
    op.add_column('user', sa.Column('oreTotal', mysql.FLOAT(), nullable=True))
    op.drop_column('user', 'minuteTotal')
    op.drop_column('user', 'minuteDarts')
    op.drop_column('user', 'minuteBowling')
    op.drop_column('user', 'minuteBiliard')
    # ### end Alembic commands ###
