"""empty message

Revision ID: f4123d3153de
Revises: bb0a748bc30c
Create Date: 2020-06-12 22:09:14.331773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4123d3153de'
down_revision = 'bb0a748bc30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('billiard_hours', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('bowling_hours', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('darts_hours', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('reservations_nr', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('telephone', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telephone')
    op.drop_column('user', 'reservations_nr')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'darts_hours')
    op.drop_column('user', 'bowling_hours')
    op.drop_column('user', 'billiard_hours')
    # ### end Alembic commands ###
